### ISSUE TITLE
Zmiana strefy czasowej i dodanie kalendarza wyboru daty

### ISSUE THREAD

**Issue by apieszczek** [apieszczek/PAI#12]
Zmienić strefę czasową w ustawieniach, żeby w ofertach wyświetlała się "po polsku". Dodać kalendarz do wyboru daty przy dodawaniu ogłoszenia.

**Comment by mpalt** [comment]
Zmieniony został sposób wyświetlania daty na język polski. Stworzony został kalendarz umożliwiający wybór daty.
