### ISSUE TITLE
Dodanie respondenta do oferty

### ISSUE THREAD

**Issue by apieszczek** [apieszczek/PAI#15]
Dodać w widoku oferty informację kto odpowiedział na tą ofertę. Dodać to do wszystkich formatek wyświetlających oferty.

**Comment by mpalt** [comment]
Dodane informacje o autorze lub respondencie w zależności od tego, czy ktoś już odpowiedział na ofertę. Dodanie komunikatu o autorze, odpowiadającym lub oczekiwaniu na odpowiedź w liście ofert. Dotyczy wszystkich formatek wyświetlających oferty
