### ISSUE TITLE
Dodanie avatarów

### ISSUE THREAD

**Issue by apieszczek** [apieszczek/PAI#3]
Dodać nazwę użytkownika i avatar na stronie profilu i ustawień.

**Comment by mpalt** [comment]
Stworzona została funkcjonalność dotycząca wyboru pliku graficznego oraz mechanizm odświeżania strony w przypadku zmiany zdjęcia. Dodano także wyświetlanie avatara w oknie profilu. Należy teraz przechować te pliki w bazie, tak aby możliwe było przypisanie zdjęcia do danego konta.

**Comment by mpalt** [comment]
Poprawiony został wygląd przycisku.

**Comment by mpalt** [comment]
Umożliwiono przypisanie obrazu do użytkownika poprzez rozszerzenie klasy User o klasę Profile. Stworzona została nowa baza z użytkownikami admin (hasło bez zmian) oraz usertest (hasło: qaz123). Wprowadzono kilka poprawek do formatek wyświetlających zdjęcie użytkownika, tak aby prawidłowo wyświetlić avatara
